package pt.uc.dei.entities;

import jakarta.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Entity representing an activation token.
 * Used for user account activation.
 */
@NamedQueries({
        @NamedQuery(
                name = "ActivationToken.findTemporaryUserByToken",
                query = "SELECT t.temporaryUser FROM ActivationTokenEntity t WHERE t.tokenValue = :tokenValue"
        ),
        @NamedQuery(
                name = "ActivationToken.findActivationTokenByValue",
                query = "SELECT t FROM ActivationTokenEntity t WHERE t.tokenValue = :tokenValue"
        ),
        @NamedQuery(
                name = "ActivationToken.findActivationTokensOfUser",
                query = "SELECT t FROM ActivationTokenEntity t WHERE t.temporaryUser.id = :id"
        )
})
@Entity
@Table(name = "activationtoken",
        indexes = @Index(name = "idx_activationtoken_tokenvalue",
                columnList = "tokenValue",
                unique = true))
/**
 * Represents an activation token used for user account verification.
 * <p>
 * Each token is uniquely generated and associated with a temporary user account
 * during the registration process.
 */
public class ActivationTokenEntity implements Serializable {

    /**
     * The unique identifier for the activation token.
     * Automatically generated by the database.
     */
    @Id
    @Column(name = "id", nullable = false, unique = true, updatable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique token string used for account activation.
     * <p>
     * Stored as a cryptographically secure random value.
     */
    @Column(name = "tokenValue", unique = true, nullable = false)
    private String tokenValue;

    /**
     * The timestamp when this token was created.
     * <p>
     * Used to determine token expiration.
     */
    @Column(name = "creation_date", nullable = false, updatable = false)
    private LocalDateTime creationDate;

    /**
     * The temporary user account associated with this activation token.
     * <p>
     * Nullable to allow for token pre-generation scenarios.
     */
    @OneToOne
    @JoinColumn(name = "temporary_user_id", nullable = true)
    private TemporaryUserEntity temporaryUser;

    // Getters and setters

    /**
     * Retrieves the activation token ID.
     *
     * @return The unique identifier of the token.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the activation token ID.
     *
     * @param id The unique identifier to be set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Retrieves the activation token value.
     *
     * @return The token string.
     */
    public String getTokenValue() {
        return tokenValue;
    }

    /**
     * Sets the activation token value.
     *
     * @param tokenValue The token string to be set.
     */
    public void setTokenValue(String tokenValue) {
        this.tokenValue = tokenValue;
    }

    /**
     * Retrieves the creation date of the activation token.
     *
     * @return The creation timestamp.
     */
    public LocalDateTime getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the creation date of the activation token.
     *
     * @param creationDate The timestamp to be set.
     */
    public void setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
    }

    public TemporaryUserEntity getTemporaryUser() {
        return temporaryUser;
    }

    public void setTemporaryUser(TemporaryUserEntity temporaryUser) {
        this.temporaryUser = temporaryUser;
    }
}