import { login } from "../../api/authenticationApi";

const en = {
  welcomeMessage: "Welcome {name}",
  goodByeMessage: "Goodbye {name}",
  //Login
  loginLogo: "CITRUS",
  loginTitle: "Login",
  loginSubtitle: "Sign-in to your account",
  loginFieldEmail: "E-mail address",
  loginFieldPassword: "Password",
  loginFieldTwoFAuth: "Two-Factor Authentication Code",
  loginShowPassword: "Show password",
  loginHidePassword: "Hide password",
  loginForgotPassword: "Forgot your password?",
  loginHelpTwoFAuth: "Need help with Two-Factor Authentication?",
  loginSubmit: "Sign in",
  loginRegisterPrompt: "Don’t have an account yet?",
  loginRegister: "Join CITRUS today.",
  passwordResetRequestSuccess: "An email has been sent to reset your password.",
  passwordResetRequestFailure:
    "Failed to send password reset email. Please try again later.",

  loginErrorEmailMissing: "Email is required",
  loginErrorEmailInvalid: "Invalid email format",
  loginErrorPasswordMissing: "Password is required",
  loginErrorAuthenticationCodeMissing: "2FA code is required",
  loginErrorAuthenticationCodeInvalid: "Invalid 2FA code",

  // Register Page
  registerTitle: "Welcome to CITRUS",
  registerSubtitle: "Register your account",
  registerFieldEmail: "E-mail address",
  registerFieldPassword: "Password",
  registerFieldConfirmPassword: "Confirm Password",
  registerShowPassword: "Show password",
  registerHidePassword: "Hide password",
  registerSubmit: "Create account",
  registerAlreadyAccount: "Already have an account?",
  registerLogin: "Log in.",
  registerLogo: "CITRUS Logo",
  registerLogoContainerTitle: "Join the CITRUS community!",
  registerButton: "Back to Login",

  registerErrorEmailMissing: "Email is required",
  registerErrorEmailInvalid: "Invalid email format",
  registerErrorPasswordMissing: "Password is required",
  registerErrorConfirmPasswordMissing: "Password confirmation is required",
  registerErrorPasswordMismatch: "Password's dont match",
  registerErrorPasswordWeak:
    "Password must be at least 12 characters long and include uppercase, lowercase, numbers, and special characters.",

  // Activation Page
  activationTitle: "Account Activation",
  activationSuccessMessage: "Account successfully created!",
  activationEmailConfirmation:
    "Your account with the email {email} has been created. " +
    "We have sent a confirmation email with a link to verify your account. " +
    "Please check your inbox.",
  activationRedirectMessage: "Redirecting to login in {segundos} seconds.",
  activatedAccountTitle: "Account activated!",
  activatedAccountMessage:
    "Your account has been activated, you can now log in.<br />Welcome to Citrus.",
  activatedAccountRedirectMessage:
    "Redirecting to login in {segundos} seconds.",
  activatedAccountButton: "Back to Login",

  //Profile
  profileUserUpdated: "Updated user successfully",

  // Forgot Password Page
  forgotPasswordTitle: "Password Reset",
  forgotPasswordSubtitle: "Write your email address",
  forgotPasswordFieldEmail: "E-mail address",
  forgotPasswordSubmit: "Reset my password",
  forgotPasswordEmailSent:
    "A password reset email has been sent to your inbox.",
  forgotPasswordEmailMissing: "Email is required",
  forgotPasswordEmailInvalid: "Invalid email format",

  //Two-Factor Authentication
  twoFactorTitle: "Setting Up 2FA",
  twoFactorWhatIsTitle: "What is Two-Factor Authentication (2FA)?",
  twoFactorWhatIsDescription:
    "Two-factor authentication adds an extra layer of security to your account. After entering your password, you'll need to enter a 6-digit code generated by an authenticator app on your phone.",
  twoFactorSetupTitle: "How to Set Up 2FA",
  twoFactorSetupStep1:
    "Open Google Authenticator, Microsoft Authenticator, or Authy.",
  twoFactorSetupStep2: "Tap 'Add a new account' and choose 'Manual Entry'.",
  twoFactorSetupStep3: "Enter the secret key below:",
  twoFactorSetupStep4:
    "Save the setup, and the app will start generating codes every 30 seconds.",
  twoFactorSecretPlaceholder: "SECRET-KEY",
  twoFactorLoginTitle: "Logging In with 2FA",
  twoFactorLoginDescription:
    "Whenever you log in, enter the latest 6-digit code shown in your authenticator app. The code changes every 30 seconds, so make sure to use the most recent one.",
  twoFactorCloseButton: "Got It!",
  twoFactorRequest: "Request Code",
  twofactorErrorEmailMissing: "Email is required",
  twofactorErrorEmailInvalid: "Invalid email format",

  //Password Reset Page
  passwordResetLogo: "CITRUS",
  passwordResetTitle: "Reset Your Password",
  passwordResetSubtitle: "Enter your new password",
  passwordResetFieldPassword: "New Password",
  passwordResetFieldConfirmPassword: "Confirm New Password",
  passwordResetShowPassword: "Show password",
  passwordResetHidePassword: "Hide password",
  passwordResetSubmit: "Reset Password",
  passwordResetErrorPasswordMissing: "Password is required",
  passwordResetErrorConfirmPasswordMissing: "Password confirmation is required",
  passwordResetErrorPasswordMismatch: "Passwords do not match",
  passwordResetErrorPasswordWeak:
    "Password must be at least 12 characters long and include uppercase, lowercase, numbers, and special characters.",
  passwordResetSuccess: "Password changed. You log in with the new password.",
  passwordResetError: "Error resetting password. Please try again later.",

  //ERRORS
  protectedRoute: "You need to be logged in to access this page",
  // General Errors
  infoAboutToExpire: "Your session is about to expire",
  inforSessionExpired: "Your session has expired. Please log in again",
  errorInvalidData: "Invalid data provided",
  errorWrongUsernamePassword: "Incorrect username or password",
  errorAccountInactive: "Your account is inactive",
  errorAccountExcluded: "Your account has been excluded",
  errorForbidden: "You don't have permission to access this resource",
  errorDuplicateEntry: "This email is already registered",
  errorServerIssue: "Server error. Please try again later",
  errorFailed: "Request failed. Please try again later",
  errorNetworkError:
    "Network error. Please check your connection or try again later",
  errorUnexpected: "An unexpected error occurred. Please try again later",
  errorInvalidCredentials: "Email or password are incorrect",
  errorInvalidAuthCode: "Invalid Two-Factor Authentication code",
  errorInvalidCodeRequest: "Email or password are incorrect",
  errorUserNotFound: "User not found",
  errorTokenExpired: "Your token has expired. Please register again.",
  errorExpiredPasswordResetToken:
    "Your password reset token has expired. Please request a new one.",

  // Validation
  errorPhoneNumberInvalid: "Invalid phone number format",
  errorEmailInvalid: "Invalid email format",

  // Not Found Page
  notfoundTitle: "404 Not Found",
  notfoundPhrase: "When life gives you lemons...",
  notfoundRedirect: "Redirecting in {segundos} seconds.",

  // PROFILE
  profileUpdateSuccess: "Profile updated successfully",
  profileUpdateError: "Error updating profile. Please try again later.",
  profileFirstName: "First Name",
  profileLastName: "Last Name",
  profileBirthDate: "Date of Birth",
  profileRole: "Role",
  profileWorkplace: "Workplace",
  profilePhone: "Phone",
  profileAddress: "Address",
  profileAddressStreet: "Street",
  profileAddressPostalCode: "Postal Code",
  profileAddressMunicipality: "Municipality",
  profileBiography: "Biography",
  profilePlaceholderNA: "N/A",
  profileSave: "Save",
  profileEdit: "Edit",
  profileCancel: "Cancel",

  // Profile Errors
  profileErrorFirstNameRequired: "First name is required",
  profileErrorLastNameRequired: "Last name is required",
  profileErrorBirthDateRequired: "Birth date is required",
  profileErrorRoleRequired: "Role is required",
  profileErrorWorkplaceRequired: "Workplace is required",
  profileErrorPhoneRequired: "Phone is required",
  profileErrorAddressRequired: "Address is required",
  profileErrorAddressStreetRequired: "Street is required",
  profileErrorAddressPostalCodeRequired: "Postal code is required",
  profileErrorAddressMunicipalityRequired: "Municipality is required",
  profileErrorBiographyRequired: "Biography is required",

  // Profile Invalid Characters
  profileErrorFirstNameInvalid: "First name contains invalid characters",
  profileErrorLastNameInvalid: "Last name contains invalid characters",
  profileErrorBirthDateFuture: "Birth date cannot be in the future",
  profileErrorBirthDateTooYoung: "You must be at least 16 years old",
  errorPostalCodeInvalid: "Invalid postal code format (e.g. 1234-567)",
  profileErrorAddressStreetInvalid: "Street contains invalid characters",
  profileErrorAddressMunicipalityInvalid:
    "Municipality contains invalid characters",

  // Profile Tabs
  profileTabProfile: "Profile",
  profileTabTraining: "Training",
  profileTabAppraisals: "Appraisals",

  //Users
  users: {
    assignManagers: "Assign Managers",
    assignManagerTitle:
      "Assign manager to {count, plural, one {# user} other {# users}}",
    willManage: "Will manage {count, plural, one {# user} other {# users}}",
    selectedUsers: "Selected users",
    selectUserToPromote: "Select a user to promote",
    promoteDescription:
      "Choose a user to promote to manager and assign selected users.",
    searchPromotePlaceholder: "Search for a user to promote...",
    willBePromoted: "will be promoted to manager.",
    cancel: "Cancel",
    assigning: "Assigning...",
    promoteAndAssign: "Promote & Assign",
    selectUserFirst: "Select a user first",
    na: "N/A",
    accountStateComplete: "Complete",
    accountStateIncomplete: "Incomplete",
    avatarLoading: "Loading...",
    viewProfile: "View Profile",
    noUsersSelected: "No users selected",
    managerAssignSuccess: "{managerName} is now the manager of {total} user(s)",
  },
  //Usercard
  userCardNoManager: "No manager",
  //Appraisal
  appraisalsNoResults: "No appraisals found matching your criteria",
  //AppraisalCard
  appraisalStateCompleted: "Complete",
  appraisalStateInProgress: "In Progress",
  appraisalStateClosed: "Closed",
  appraisalsPdfExportError: "Failed to export appraisals to PDF. Please try again later.",

  //Searchbar
  searchBarSearchButton: "Search",
  searchBarPlaceholder: "Search by {type}…",
  searchBarAllStates: "All States",
  searchBarComplete: "Complete",
  searchBarIncomplete: "Incomplete",
  searchBarLimitToggle: "Results per page",
  searchByEmail: "email",
  searchByName: "name",
  searchByRole: "role",


  //User Sort Controls
  userSortControlsName: "Name",
  userSortControlsRole: "Role",
  userSortControlsOffice: "Office",
  userSortControlsManager: "Manager",
  userSortControlsSortAscending: "Sort ascending",
  userSortControlsSortDescending: "Sort descending",

  //Appraisal Sort Controls
  appraisalSortControlsUser: "User",
  appraisalSortControlsScore: "Score",
  appraisalSortControlsManager: "Manager",
  appraisalSortControlsEndDate: "End Date",
  appraisalSortControlsState: "State",

  //Filtermenu
  filterMenuSettings: "Filters",
  filterMenuSearchType: "Search Type",
  filterMenuOptionName: "Name",
  filterMenuOptionEmail: "Email",
  filterMenuOptionRole: "Role",
  filterMenuState: "State",
  filterMenuOffice: "Office",
  filterMenuAllOffices: "All Offices",
  filterMenuAccountState: "Account State",
  filterMenuOptionComplete: "Complete",
  filterMenuOptionIncomplete: "Incomplete",
  filterMenuisManager: "Show only managers",
  filterMenuisAdmin: "Show only admins",
  filterMenuisManaged: "Managed users",

  // Menu internationalization
  menuDashboard: "Dashboard",
  menuProfile: "Profile",
  menuUsers: "Users",
  menuTraining: "Training",
  menuAppraisal: "Appraisal",
  menuCycles: "Cycles",
  menuSettings: "Settings",
  menuDarkMode: "Dark Mode",
  menuDarkModeBeta: "Beta",
  menuLanguage: "Language",
  menuLogout: "Logout",

  // Message Center
  messageCenter: {
    searchPlaceholder: "Search for user to start conversation...",
    lastOnlineAt: "Last online at",
    statusSending: "⏳",
    statusFailed: "❌",
    statusSent: "✓",
    statusRead: "✓✓",
    statusNotRead: "✓✓",
    typeMessage: "Type a message...",
    selectConversation: "Select a conversation to start chatting",
  },

  // Appraisals Search
  appraisalsSearchTypeUserName: "user name",
  appraisalsSearchTypeUserEmail: "user email",
  appraisalsSearchTypeManagerName: "manager name",
  appraisalsSearchTypeManagerEmail: "manager email",
  appraisalStateAllStates: "all states",

  appraisal: {
    scoreVerbose: {
      null: "No score assigned",
      1: "Low contribution",
      2: "Partial contribution",
      3: "Expected contribution",
      4: "Exceeded contribution"
    },
    submit: "Submit",
    save: "Save",
    saved: "Saved appraisal. You can submit until {endDate}",
    saving: "Saving...",
    submitted: "Appraisal submitted successfully.",
    cancel: "Cancel",
    edit: "Edit",
    feedback: "Feedback",
    feedbackText: "Feedback text",
    score: "Score",
    noFeedback: "No feedback provided.",
    saveError: "Failed to save appraisal.",
    noAppraisalsSelected: "No appraisals selected",
    completeAppraisals: "Complete",
    pdfGenerated: "PDF generated successfully. You can download it now.",
    pdfGenerationFailed: "Failed to generate PDF. Please try again later.",

  },

};
export default en;
