--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-07-13 17:41:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 45013)
-- Name: message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message (
    id bigint NOT NULL,
    is_read boolean NOT NULL,
    message_content character varying(255) NOT NULL,
    sent_date timestamp(6) without time zone NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.message OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 45012)
-- Name: message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4839 (class 0 OID 45013)
-- Dependencies: 219
-- Data for Name: message; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (65, false, 'estás online?', '2025-07-03 00:56:07.608328', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (66, false, 'Não? Então vai à merda', '2025-07-03 00:56:16.564704', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (67, false, 'Estou para aqui a falar sozinho', '2025-07-03 00:56:27.123894', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (68, false, 'estou a falar sozinho digo', '2025-07-03 00:56:36.844872', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (69, false, 'Não estou? Oi?', '2025-07-03 00:56:43.98747', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (44, false, 'teeste', '2025-07-01 23:35:00.451916', 5, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (70, false, '😂', '2025-07-03 00:56:57.749877', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (45, false, 'testes', '2025-07-02 11:04:12.975793', 3, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (47, false, 'io', '2025-07-02 11:04:30.179863', 10, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (49, false, 'tudo bem', '2025-07-02 11:04:43.304378', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (51, true, 'teste', '2025-07-02 15:35:36.69962', 2, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (55, true, 'etetes', '2025-07-02 15:44:32.074506', 2, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (56, true, 'teste', '2025-07-02 15:44:59.793312', 2, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (114, true, 'Break', '2025-07-12 18:12:35.967752', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (115, true, 'teste', '2025-07-12 18:12:42.683742', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (116, true, 'tste', '2025-07-12 18:12:43.89376', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (117, true, 'devem haver 3 message count', '2025-07-12 18:12:53.22785', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (101, true, 'Adn lá responde', '2025-07-12 18:05:48.854235', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (86, true, 'oopoppp', '2025-07-06 17:26:43.869569', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (83, true, 'j', '2025-07-06 17:25:21.350798', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (78, true, 'bet', '2025-07-06 17:17:58.410563', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (126, true, 'outro test', '2025-07-13 12:32:32.872508', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (127, true, 'mais yum', '2025-07-13 12:32:35.583348', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (124, true, 'teste outra vez', '2025-07-13 12:25:53.6399', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (109, true, 'BREAK', '2025-07-12 18:10:09.562746', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (80, true, 'girafa', '2025-07-06 17:23:20.938595', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (81, true, 'hiena', '2025-07-06 17:23:25.865148', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (82, true, 'iguana', '2025-07-06 17:23:33.85716', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (73, true, 'teste', '2025-07-06 17:14:09.711395', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (79, true, 'charlie', '2025-07-06 17:18:00.498062', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (74, true, 'teste', '2025-07-06 17:14:59.642444', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (75, true, 'teste', '2025-07-06 17:15:11.372635', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (87, true, 'test', '2025-07-06 17:31:24.887469', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (128, true, 'paneleirote de um raio', '2025-07-13 17:21:44.727747', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (88, true, 'te', '2025-07-06 17:31:25.379405', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (89, true, 'teste', '2025-07-06 17:31:26.363355', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (90, true, 'teste', '2025-07-06 17:33:18.913585', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (129, true, 'ès um oanasca', '2025-07-13 17:21:49.957175', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (43, true, 'teste', '2025-07-01 22:11:19.051105', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (61, true, 'Então tudo bem?', '2025-07-02 22:01:12.134052', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (76, true, 'teste', '2025-07-06 17:15:26.480594', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (9, true, 'Macaco és tu', '2025-06-30 23:29:52.686733', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (10, true, 'Tu é que és macaco', '2025-07-01 00:16:05.319347', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (17, true, 'teste', '2025-07-01 17:18:56.096521', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (11, true, 'teste', '2025-07-01 17:01:39.969286', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (27, true, 'então?', '2025-07-01 17:31:46.251291', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (29, true, 'e tu?', '2025-07-01 17:32:08.147344', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (99, true, 'estás online?', '2025-07-12 18:05:24.286189', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (100, true, 'Está ou não', '2025-07-12 18:05:30.041932', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (105, true, 'cavalo', '2025-07-12 18:07:59.567953', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (18, true, 'teste', '2025-07-01 17:19:35.995803', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (19, true, 'teste', '2025-07-01 17:22:04.291726', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (20, true, 'teste', '2025-07-01 17:22:35.442355', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (106, true, 'vou sair daqui', '2025-07-12 18:08:06.049172', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (121, true, 'teste', '2025-07-13 12:05:24.482744', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (122, true, 'teste', '2025-07-13 12:25:32.752833', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (123, true, 'teste', '2025-07-13 12:25:38.358961', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (130, true, 'TU és um panasca', '2025-07-13 17:21:55.384751', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (52, true, 'teste', '2025-07-02 15:43:15.663494', 2, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (53, true, 'toep', '2025-07-02 15:43:22.836412', 2, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (57, false, 'da', '2025-07-02 15:45:55.901039', 4, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (58, false, 'teste', '2025-07-02 15:47:00.184914', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (59, false, 'teste', '2025-07-02 15:57:48.951012', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (60, false, 'Olá olga', '2025-07-02 15:58:00.391669', 17, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (46, false, 'yo', '2025-07-02 11:04:22.56702', 4, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (48, false, 'olá', '2025-07-02 11:04:36.193821', 18, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (50, false, 'está tudo', '2025-07-02 11:04:54.890123', 12, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (54, true, 'teste', '2025-07-02 15:43:36.087425', 2, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (125, true, 'teste outravez', '2025-07-13 12:29:02.381279', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (118, true, 'Estás online?', '2025-07-13 00:06:42.665642', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (119, true, 'És um palhaço', '2025-07-13 00:06:46.687933', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (120, true, 'Tu és um palhaço', '2025-07-13 00:06:53.958076', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (110, true, 'Formiga', '2025-07-12 18:10:22.788564', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (111, true, 'Camaleão', '2025-07-12 18:10:27.150515', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (112, true, 'Elefant', '2025-07-12 18:10:30.68549', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (91, true, 'testetete', '2025-07-06 17:33:29.890833', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (92, true, 'lopop', '2025-07-06 17:33:32.636072', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (41, true, 'teste', '2025-07-01 22:08:54.347968', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (40, true, 'ta', '2025-07-01 22:07:04.138627', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (38, true, 'teste', '2025-07-01 22:04:20.250519', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (35, true, 'tigre', '2025-07-01 17:48:06.959521', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (7, true, 'olá macaco', '2025-06-30 23:25:09.403082', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (8, true, 'olá macaco', '2025-06-30 23:28:29.27875', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (12, true, 'filha da puta passates', '2025-07-01 17:04:29.892212', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (13, true, 'merdas', '2025-07-01 17:13:24.399265', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (14, true, 'teste', '2025-07-01 17:14:46.63974', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (15, true, 'as', '2025-07-01 17:17:40.348124', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (16, true, 'teste', '2025-07-01 17:18:25.939182', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (30, true, 'estás tudo?', '2025-07-01 17:34:15.115375', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (32, true, 'está tudo?', '2025-07-01 17:36:08.192328', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (131, true, 'Vai ta foder, panasca és tu', '2025-07-13 17:22:49.040786', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (132, true, 'Paneleirote', '2025-07-13 17:22:55.795006', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (34, true, 'leão', '2025-07-01 17:47:21.472262', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (98, true, 'És um palhado', '2025-07-06 17:42:17.191943', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (42, true, 'teste', '2025-07-01 22:09:23.616717', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (62, true, 'Está tudo e tu?', '2025-07-02 22:01:18.626905', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (95, true, 'É AGORAAAAA!!!!!', '2025-07-06 17:38:22.585417', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (97, true, 'FINALMENTE', '2025-07-06 17:41:32.708545', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (96, true, 'FINALMENTE É AGORA', '2025-07-06 17:40:14.74105', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (63, true, 'Então vai te lá embora', '2025-07-02 22:01:27.577621', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (64, true, 'Olá', '2025-07-02 22:01:48.292614', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (77, true, 'albano', '2025-07-06 17:17:52.455128', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (93, true, 'estas ai?', '2025-07-06 17:35:38.773617', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (102, true, 'zebra', '2025-07-12 18:06:46.685522', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (103, true, 'cabra', '2025-07-12 18:06:48.15595', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (21, true, 'teste', '2025-07-01 17:23:40.416179', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (22, true, 'teste', '2025-07-01 17:24:09.832021', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (23, true, 'teste', '2025-07-01 17:28:47.855066', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (24, true, 'teste', '2025-07-01 17:30:02.455148', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (25, true, 'filho da puta', '2025-07-01 17:30:45.700317', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (26, true, 'yes!!!!', '2025-07-01 17:31:08.96462', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (28, true, 'está tudo', '2025-07-01 17:32:01.052693', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (31, true, 'eu estou', '2025-07-01 17:34:21.764659', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (33, true, 'zebra', '2025-07-01 17:47:08.822022', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (36, true, 'teste', '2025-07-01 22:01:52.403605', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (37, true, 'teste', '2025-07-01 22:02:10.455281', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (39, true, 'fa', '2025-07-01 22:05:55.234275', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (113, true, 'Brek again', '2025-07-12 18:12:31.691665', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (133, true, 'És tu, tu é que és', '2025-07-13 17:23:13.771222', 2, 1);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (104, true, 'porco', '2025-07-12 18:06:49.181121', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (107, true, 'ovelha', '2025-07-12 18:08:16.772291', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (108, true, 'leão', '2025-07-12 18:08:19.308226', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (72, true, 'Este chat está a funcionar que é uma maravilha não é?', '2025-07-03 00:57:22.780773', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (71, true, 'Está espetáculo digo', '2025-07-03 00:57:08.416661', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (84, true, 'k', '2025-07-06 17:25:25.829563', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (85, true, 'l', '2025-07-06 17:25:25.86447', 1, 2);
INSERT INTO public.message (id, is_read, message_content, sent_date, receiver_id, sender_id) VALUES (94, true, 'TESTE FINAL', '2025-07-06 17:37:34.061468', 1, 2);


--
-- TOC entry 4845 (class 0 OID 0)
-- Dependencies: 218
-- Name: message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.message_id_seq', 133, true);


--
-- TOC entry 4690 (class 2606 OID 45017)
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- TOC entry 4687 (class 1259 OID 70851)
-- Name: idx_conversation_pair; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_conversation_pair ON public.message USING btree (receiver_id, sender_id, sent_date);


--
-- TOC entry 4688 (class 1259 OID 70850)
-- Name: idx_recipient_sender_unread; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_recipient_sender_unread ON public.message USING btree (receiver_id, sender_id, is_read);


--
-- TOC entry 4691 (class 2606 OID 46034)
-- Name: message fk6upx6isb2via0kq9o7dvdwjpe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk6upx6isb2via0kq9o7dvdwjpe FOREIGN KEY (sender_id) REFERENCES public.useraccount(id);


--
-- TOC entry 4692 (class 2606 OID 46029)
-- Name: message fkpx622ehc3dftq16m9yq2n7mm0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fkpx622ehc3dftq16m9yq2n7mm0 FOREIGN KEY (receiver_id) REFERENCES public.useraccount(id);


-- Completed on 2025-07-13 17:41:32

--
-- PostgreSQL database dump complete
--

