--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-07-13 17:50:13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 239 (class 1259 OID 72742)
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    creation_date timestamp(6) without time zone NOT NULL,
    message_count integer NOT NULL,
    is_read boolean NOT NULL,
    is_seen boolean NOT NULL,
    type character varying(255) NOT NULL,
    sender_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['MESSAGE'::character varying, 'APPRAISAL'::character varying, 'CYCLE'::character varying, 'COURSE'::character varying])::text[])))
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 72741)
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4838 (class 0 OID 72742)
-- Dependencies: 239
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (2, '2025-07-21', '2025-07-13 15:56:53.072596', 0, false, false, 'CYCLE', 1, 6);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (3, '2025-07-21', '2025-07-13 15:56:53.083569', 0, false, false, 'CYCLE', 1, 10);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (4, '2025-07-21', '2025-07-13 15:56:53.095534', 0, false, false, 'CYCLE', 1, 12);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (5, '2025-07-21', '2025-07-13 15:56:53.104511', 0, false, false, 'CYCLE', 1, 4);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (6, '2025-07-21', '2025-07-13 15:56:53.113486', 0, false, false, 'CYCLE', 1, 7);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (8, '2025-07-21', '2025-07-13 15:56:53.129444', 0, false, false, 'CYCLE', 1, 17);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (9, '2025-07-21', '2025-07-13 15:56:53.141413', 0, false, false, 'CYCLE', 1, 19);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (10, '2025-07-21', '2025-07-13 15:56:53.152383', 0, false, false, 'CYCLE', 1, 25);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (11, '2025-07-21', '2025-07-13 15:56:53.162357', 0, false, false, 'CYCLE', 1, 3);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (7, '2025-07-21', '2025-07-13 15:56:53.120467', 0, true, true, 'CYCLE', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (14, 'N/A', '2025-07-13 15:58:43.231432', 0, false, false, 'APPRAISAL', 12, 3);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (15, 'N/A', '2025-07-13 15:58:43.247388', 0, false, false, 'APPRAISAL', 12, 4);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (16, 'N/A', '2025-07-13 15:58:43.255366', 0, false, false, 'APPRAISAL', 12, 5);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (17, 'N/A', '2025-07-13 15:58:43.265342', 0, false, false, 'APPRAISAL', 2, 6);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (18, 'N/A', '2025-07-13 15:58:43.271323', 0, false, false, 'APPRAISAL', 1, 7);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (19, 'N/A', '2025-07-13 15:58:43.280299', 0, false, false, 'APPRAISAL', 1, 9);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (20, 'N/A', '2025-07-13 15:58:43.289276', 0, false, false, 'APPRAISAL', 2, 10);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (21, 'N/A', '2025-07-13 15:58:43.299249', 0, false, false, 'APPRAISAL', 1, 11);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (22, 'N/A', '2025-07-13 15:58:43.305233', 0, false, false, 'APPRAISAL', 1, 12);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (23, 'N/A', '2025-07-13 15:58:43.313212', 0, false, false, 'APPRAISAL', 1, 13);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (24, 'N/A', '2025-07-13 15:58:43.32119', 0, false, false, 'APPRAISAL', 1, 14);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (25, 'N/A', '2025-07-13 15:58:43.32917', 0, false, false, 'APPRAISAL', 1, 15);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (26, 'N/A', '2025-07-13 15:58:43.33615', 0, false, false, 'APPRAISAL', 1, 16);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (27, 'N/A', '2025-07-13 15:58:43.34413', 0, false, false, 'APPRAISAL', 1, 17);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (28, 'N/A', '2025-07-13 15:58:43.352108', 0, false, false, 'APPRAISAL', 1, 18);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (29, 'N/A', '2025-07-13 15:58:43.360086', 0, false, false, 'APPRAISAL', 1, 19);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (30, 'N/A', '2025-07-13 15:58:43.368065', 0, false, false, 'APPRAISAL', 1, 20);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (31, 'N/A', '2025-07-13 15:58:43.37405', 0, false, false, 'APPRAISAL', 1, 22);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (32, 'N/A', '2025-07-13 15:58:43.384023', 0, false, false, 'APPRAISAL', 1, 23);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (33, 'N/A', '2025-07-13 15:58:43.392001', 0, false, false, 'APPRAISAL', 1, 24);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (34, 'N/A', '2025-07-13 15:58:43.402973', 0, false, false, 'APPRAISAL', 1, 25);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (35, 'N/A', '2025-07-13 15:58:43.413945', 0, false, false, 'APPRAISAL', 2, 128);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (12, '4', '2025-07-13 15:58:43.213478', 0, true, true, 'APPRAISAL', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (36, 'React Fundamentals', '2025-07-13 17:16:29.364388', 0, true, true, 'COURSE', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (37, 'Java Spring Boot', '2025-07-13 17:16:29.424228', 0, true, true, 'COURSE', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (38, 'Vue.js Development', '2025-07-13 17:16:29.461131', 0, true, true, 'COURSE', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (39, 'UI/UX Design Principles', '2025-07-13 17:17:03.958752', 0, true, true, 'COURSE', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (40, 'Docker & Kubernetes', '2025-07-13 17:19:13.413478', 0, true, true, 'COURSE', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (13, 'N/A', '2025-07-13 15:58:43.22046', 0, true, false, 'APPRAISAL', 1, 1);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (1, '2025-07-21', '2025-07-13 15:56:53.042676', 0, true, false, 'CYCLE', 1, 1);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (41, 'TU és um panasca', '2025-07-13 17:21:44.743667', 0, true, true, 'MESSAGE', 1, 2);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (42, 'Paneleirote', '2025-07-13 17:22:49.051756', 0, true, true, 'MESSAGE', 2, 1);
INSERT INTO public.notification (id, content, creation_date, message_count, is_read, is_seen, type, sender_id, user_id) VALUES (43, 'És tu, tu é que és', '2025-07-13 17:23:13.777205', 0, true, true, 'MESSAGE', 1, 2);


--
-- TOC entry 4844 (class 0 OID 0)
-- Dependencies: 238
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 43, true);


--
-- TOC entry 4689 (class 2606 OID 72749)
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- TOC entry 4690 (class 2606 OID 72756)
-- Name: notification fk85p302jirte2er6pwfjvn126i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk85p302jirte2er6pwfjvn126i FOREIGN KEY (sender_id) REFERENCES public.useraccount(id);


--
-- TOC entry 4691 (class 2606 OID 72761)
-- Name: notification fk8ebbxu05xjwphoxnvtwlcg46s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk8ebbxu05xjwphoxnvtwlcg46s FOREIGN KEY (user_id) REFERENCES public.useraccount(id);


-- Completed on 2025-07-13 17:50:13

--
-- PostgreSQL database dump complete
--

